### ISSUE TITLE
"pipx install"ed version fails

### ISSUE THREAD

**Issue by jepler** [dpohanlon/mesh-tumbler#1]
```
$ pipx install .
  installed package mesh-tumbler 0.1.0, installed using Python 3.11.2
  These apps are now globally available
    - mesh-tumbler
done! ✨ 🌟 ✨
$ mesh-tumbler input.stl
Traceback (most recent call last):
  File "/home/jepler/.local/bin/mesh-tumbler", line 5, in <module>
    from mesh_tumbler.rotate_mesh import run
  File "/home/jepler/.local/pipx/venvs/mesh-tumbler/lib/python3.11/site-packages/mesh_tumbler/rotate_mesh.py", line 4, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
```

I did not file a PR to depend on tqdm in part because tqdm is only used inside an unused function. However, with this modification, the pipx-installed version did run:

```diff
diff --git a/pyproject.toml b/pyproject.toml
index c773790..81e5133 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -16,6 +16,7 @@ pandas = "<=2.1.4"
 seaborn = "^0.13.2"
 matplotlib = "^3.9.0"
 trimesh = "^4.4.1"
+tqdm = "^4.66.4"
 
 
 [build-system]
```

**Comment by jepler** [comment]
Thank you

**Comment by dpohanlon** [comment]
Thanks for reporting!
